### ISSUE TITLE
[Bug] Crash on exiting world when resolution is set to "Native"

### ISSUE THREAD

**Issue by spacky1** [Minenash/Seamless-Loading-Screen#92] opened 2023-10-13 20:01 UTC
[latest.log](https://github.com/Minenash/Seamless-Loading-Screen/files/12898430/latest.log)

**Comment by Dragon-Seeker** [comment] 2023-10-14 03:36
Hmmm such a bug was not caught for a long time, this is caused by setting the Frame Buffer of the given window to 0 width and height. Ill see about getting such fixed coming up

**Comment by Aces-and-Jacks** [comment] 2023-10-27 00:11
Can you also apply this fix to 1.19.2?

**Comment by Dragon-Seeker** [comment] 2023-11-06 23:13
> Can you also apply this fix to 1.19.2?

Possibly

**Comment by Dragon-Seeker** [comment] 2024-01-07 07:23
This is fixed in later versions and a backport is not going to happen due to not having time for such

**Closed as completed by Dragon-Seeker** 2024-01-07 07:23 UTC
Labels: bug
