### ISSUE TITLE
[Bug] Crash on config Load due to old Config

### ISSUE THREAD

**Issue by Jim3535** [Minenash/Seamless-Loading-Screen#89] opened 2023-09-11 18:19 UTC
The latest update crashes when trying to launch minecraft with fabric. This happens both with and without yet another config lib.

The issue reproduces in my test instance with just fabric api and the seamless loading screen mod enabled.

Prism launcher
Minecraft: 1.20.1
fabricloader 0.14.22
Mod version: seamless_loading_screen 2.0.2+1.20.1

```
---- Minecraft Crash Report ----
// Uh... Did I do that?
Time: 2023-09-11 11:06:22
Description: Initializing game
java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'seamless_loading_screen'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
	at net.minecraft.class_310.<init>(class_310.java:458)
	at net.minecraft.client.main.Main.main(Main.java:211)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)
Caused by: java.lang.UnsupportedOperationException: JsonObject
	at com.google.gson.JsonElement.getAsInt(JsonElement.java:239)
	at dev.isxander.yacl3.config.GsonConfigInstance$ColorTypeAdapter.deserialize(GsonConfigInstance.java:108)
	at dev.isxander.yacl3.config.GsonConfigInstance$ColorTypeAdapter.deserialize(GsonConfigInstance.java:105)
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:76)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.readIntoField(ReflectiveTypeAdapterFactory.java:212)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$FieldReflectionAdapter.readField(ReflectiveTypeAdapterFactory.java:431)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:391)
	at com.google.gson.Gson.fromJson(Gson.java:1214)
	at com.google.gson.Gson.fromJson(Gson.java:1124)
	at com.google.gson.Gson.fromJson(Gson.java:1034)
	at com.google.gson.Gson.fromJson(Gson.java:969)
	at dev.isxander.yacl3.config.GsonConfigInstance.load(GsonConfigInstance.java:83)
	at com.minenash.seamless_loading_screen.config.Config.load(Config.java:35)
	at com.minenash.seamless_loading_screen.SeamlessLoadingScreen.onInitializeClient(SeamlessLoadingScreen.java:23)
	at com.minenash.seamless_loading_screen.fabric.SeamlessLoadingScreenFabric.onInitializeClient(SeamlessLoadingScreenFabric.java:29)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 10 more
A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------
-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
	at net.minecraft.class_310.<init>(class_310.java:458)
```

[latest.log](https://github.com/Minenash/Seamless-Loading-Screen/files/12579182/latest.log)
[crash-2023-09-11_11.06.22-client.txt](https://github.com/Minenash/Seamless-Loading-Screen/files/12579181/crash-2023-09-11_11.06.22-client.txt)

**Comment by Dragon-Seeker** [comment] 2023-09-11 19:34
This is caused by a Config Issue that existed before hand that is leading to this issue, try deleting the config file to stop the crash.

**Comment by Jim3535** [comment] 2023-09-11 19:50
Removing the config file does fix the crash

**Comment by Dragon-Seeker** [comment] 2023-09-11 19:59
I am talking about replacing the config system for something else due to the mishandling of the API and the release cycle for which an update to fix the bug.

**Comment by EGOIST1372** [comment] 2023-09-12 00:00
Time: 2023-09-12 04:23:53
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'seamless_loading_screen'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
	at net.minecraft.class_310.<init>(class_310.java:458)
	at net.minecraft.client.main.Main.main(Main.java:211)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.UnsupportedOperationException: JsonObject
	at com.google.gson.JsonElement.getAsInt(JsonElement.java:239)
	at dev.isxander.yacl3.config.GsonConfigInstance$ColorTypeAdapter.deserialize(GsonConfigInstance.java:108)
	at dev.isxander.yacl3.config.GsonConfigInstance$ColorTypeAdapter.deserialize(GsonConfigInstance.java:105)
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:76)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.readIntoField(ReflectiveTypeAdapterFactory.java:212)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$FieldReflectionAdapter.readField(ReflectiveTypeAdapterFactory.java:431)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:391)
	at com.google.gson.Gson.fromJson(Gson.java:1214)
	at com.google.gson.Gson.fromJson(Gson.java:1124)
	at com.google.gson.Gson.fromJson(Gson.java:1034)
	at com.google.gson.Gson.fromJson(Gson.java:969)
	at dev.isxander.yacl3.config.GsonConfigInstance.load(GsonConfigInstance.java:83)
	at com.minenash.seamless_loading_screen.config.Config.load(Config.java:35)
	at com.minenash.seamless_loading_screen.SeamlessLoadingScreen.onInitializeClient(SeamlessLoadingScreen.java:23)
	at com.minenash.seamless_loading_screen.fabric.SeamlessLoadingScreenFabric.onInitializeClient(SeamlessLoadingScreenFabric.java:29)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 7 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
	at net.minecraft.class_310.<init>(class_310.java:458)
Mixins in Stacktrace:
	net.minecraft.class_310:
		io.wispforest.owo.mixin.MinecraftClientMixin (owo.mixins.json)
		fuzs.forgeconfigapiport.mixin.client.MinecraftMixin (forgeconfigapiport.common.mixins.json)
		de.maxhenkel.camerautils.mixin.MinecraftMixin (camerautils.mixins.json)
		net.fabricmc.fabric.mixin.event.lifecycle.client.MinecraftClientMixin (fabric-lifecycle-events-v1.client.mixins.json)
		com.tterrag.blur.mixin.MixinMinecraftClient (mixins.blur.json)
		malte0811.ferritecore.mixin.fabric.MinecraftMixin (ferritecore.fabric.mixin.json)
		randommcsomethin.fallingleaves.mixin.MinecraftClientMixin (fallingleaves.mixins.json)
		net.xolt.freecam.mixins.MinecraftClientMixin (freecam.mixins.json)
		dev.lambdaurora.spruceui.mixin.MinecraftClientMixin (spruceui.mixins.json)
		dev.hephaestus.atmosfera.mixin.MinecraftClientMixin (atmosfera.mixins.json)
		opekope2.optigui.mixin.MinecraftClientMixin2 (optigui.mixins.json)
		net.blay09.mods.balm.mixin.MinecraftMixin (balm.mixins.json)
		de.guntram.mcmod.clickthrough.mixins.ItemUseMixin (mixins.clickthrough.json)
		dev.stashy.extrasounds.mixin.inventory.MinecraftClientMixin (extrasounds.mixins.json)
		de.keksuccino.konkrete.mixin.mixins.client.MixinMinecraft (konkrete.mixin.json)
		fi.dy.masa.minihud.mixin.MixinMinecraftClient (mixins.minihud.json)
		com.anthonyhilyard.prism.mixin.MinecraftMixin (prism.mixins.json)
		net.fabricmc.fabric.mixin.event.interaction.client.MinecraftClientMixin (fabric-events-interaction-v0.client.mixins.json)
		com.blamejared.controlling.mixin.OpenGuiMixin (controlling.fabric.mixins.json)
		io.github.cottonmc.cotton.gui.impl.mixin.client.MinecraftClientMixin (mixins.libgui.json)
		de.maxhenkel.voicechat.mixin.MinecraftMixin (voicechat.mixins.json)
		de.keksuccino.drippyloadingscreen.mixin.mixins.client.MixinMinecraft (drippyloadingscreen.mixin.json)
		io.grayray75.mods.fpsdisplay.mixin.MinecraftClientAccessor (fpsdisplay.mixins.json)
		dev.tr7zw.itemswapper.mixin.MinecraftMixin (itemswapper.mixins.json)
		fi.dy.masa.malilib.mixin.MixinMinecraftClient (mixins.malilib.json)
		de.johni0702.minecraft.bobby.mixin.MinecraftClientMixin (bobby.mixins.json)
		org.anti_ad.mc.ipnext.mixin.MixinMinecraftClient (mixins.ipnext.json)
		de.keksuccino.auudio.mixin.client.MixinMinecraft (auudio.mixin.json)
		draylar.omegaconfig.mixin.ClientMixin (omega-config.mixins.json)
		dev.tr7zw.exordium.mixin.MinecraftMixin (exordium.mixins.json)
		net.fabricmc.fabric.mixin.datagen.client.MinecraftClientMixin (fabric-data-generation-api-v1.client.mixins.json)
		com.blamejared.ambientenvironment.mixin.MixinMinecraft (ambientenvironment.fabric.mixins.json)
		net.darkhax.bookshelf.mixin.accessors.client.AccessorMinecraft (bookshelf.common.mixins.json)
		net.fabricmc.fabric.mixin.screen.MinecraftClientMixin (fabric-screen-api-v1.mixins.json)
		com.minelittlepony.common.mixin.MixinMinecraftClient (kirin.mixin.json)
		ladysnake.satin.mixin.client.event.MinecraftClientMixin (mixins.satin.client.json)
		dev.stashy.extrasounds.mixin.hotbar.MinecraftClientMixin (extrasounds.mixins.json)
		dlovin.inventoryhud.mixin.PlayerMixin (inventoryhud.mixins.json)
		com.anthonyhilyard.iceberg.mixin.MinecraftMixin (iceberg.mixins.json)
		net.coderbot.iris.mixin.MixinMinecraft_Images (mixins.iris.json)
		de.maxhenkel.status.mixin.MinecraftMixin (status.mixins.json)
		de.keksuccino.fancymenu.mixin.client.IMixinMinecraft (fancymenu.general.mixin.json)
		com.glisco.isometricrenders.mixin.MinecraftClientMixin (isometric-renders.mixins.json)
		com.natamus.collective.fabric.mixin.MinecraftMixin (collective_fabric.mixins.json)
		traben.entity_texture_features.mixin.reloading.MixinMinecraftClient (entity_texture_features-common.mixins.json)
		de.keksuccino.drippyloadingscreen.mixin.mixins.client.IMixinMinecraft (drippyloadingscreen.mixin.json)
		net.coderbot.iris.mixin.MixinMinecraft_Keybinds (mixins.iris.json)
		me.jellysquid.mods.sodium.mixin.core.MinecraftClientMixin (sodium.mixins.json)
		me.flashyreese.mods.sodiumextra.mixin.gui.MinecraftClientAccessor (sodium-extra.mixins.json)
		traben.entity_texture_features.mixin.reloading.MixinResourceReload (entity_texture_features-common.mixins.json)
		net.fabricmc.fabric.mixin.networking.client.accessor.MinecraftClientAccessor (fabric-networking-api-v1.client.mixins.json)
		net.coderbot.iris.mixin.MixinMinecraft_PipelineManagement (mixins.iris.json)
		de.keksuccino.fancymenu.mixin.client.MixinMinecraft (fancymenu.general.mixin.json)
		net.fabricmc.fabric.mixin.registry.sync.client.MinecraftClientMixin (fabric-registry-sync-v0.client.mixins.json)
		obro1961.chatpatches.mixin.MinecraftClientMixin (chatpatches.mixins.json)
		dev.architectury.mixin.fabric.client.MixinMinecraft (architectury.mixins.json)
		com.minenash.seamless_loading_screen.mixin.MinecraftClientMixin (seamless_loading_screen-common.mixins.json)
		shcm.shsupercm.fabric.citresewn.defaults.mixin.types.enchantment.MinecraftClientMixin (citresewn-defaults.mixins.json)
		dynamic_fps.impl.mixin.MinecraftMixin (dynamic_fps.mixins.json)
		com.gpumemleakfix.mixin.ClientTickMixin (gpumemleakfix.mixins.json)
		de.maxhenkel.peek.mixin.MinecraftMixin (peek.mixins.json)
		dev.isxander.yacl3.mixin.MinecraftMixin (yacl.mixins.json)
		io.wispforest.owo.mixin.ui.MinecraftClientMixin (owo.mixins.json)
		dzwdz.chat_heads.mixin.MinecraftMixin (chat_heads.mixins.json)
		opekope2.optigui.mixin.MinecraftClientMixin (optigui.mixins.json)

-- Initialization --
Details:
	Modules: 
		ADVAPI32.dll:Advanced Windows 32 Base API:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		AUDIOSES.DLL:Audio Session:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		AVRT.dll:Multimedia Realtime Runtime:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		COMCTL32.dll:User Experience Controls Library:6.10 (WinBuild.160101.0800):Microsoft Corporation
		CRYPT32.dll:Crypto API32:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		CRYPTBASE.dll:Base cryptographic API DLL:10.0.19041.546 (WinBuild.160101.0800):Microsoft Corporation
		CRYPTSP.dll:Cryptographic Service Provider API:10.0.19041.546 (WinBuild.160101.0800):Microsoft Corporation
		DBGHELP.DLL:Windows Image Helper:10.0.19041.867 (WinBuild.160101.0800):Microsoft Corporation
		DEVOBJ.dll:Device Information Set DLL:10.0.19041.3155 (WinBuild.160101.0800):Microsoft Corporation
		DNSAPI.dll:DNS Client API DLL:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		DSOUND.dll:DirectSound:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		GDI32.dll:GDI Client DLL:10.0.19041.2913 (WinBuild.160101.0800):Microsoft Corporation
		IMM32.DLL:Multi-User Windows IMM32 API Client DLL:10.0.19041.2673 (WinBuild.160101.0800):Microsoft Corporation
		IPHLPAPI.DLL:IP Helper API:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		KERNEL32.DLL:Windows NT BASE API Client DLL:10.0.19041.3155 (WinBuild.160101.0800):Microsoft Corporation
		KERNELBASE.dll:Windows NT BASE API Client DLL:10.0.19041.3155 (WinBuild.160101.0800):Microsoft Corporation
		MMDevApi.dll:MMDevice API:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		MSACM32.dll:Microsoft ACM Audio Filter:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		MSCTF.dll:MSCTF Server DLL:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		NLAapi.dll:Network Location Awareness 2:10.0.19041.3031 (WinBuild.160101.0800):Microsoft Corporation
		NSI.dll:NSI User-mode interface DLL:10.0.19041.610 (WinBuild.160101.0800):Microsoft Corporation
		NTASN1.dll:Microsoft ASN.1 API:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		OLEAUT32.dll:OLEAUT32.DLL:10.0.19041.3208 (WinBuild.160101.0800):Microsoft Corporation
		PSAPI.DLL:Process Status Helper:10.0.19041.546 (WinBuild.160101.0800):Microsoft Corporation
		Pdh.dll:Windows Performance Data Helper DLL:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		RPCRT4.dll:Remote Procedure Call Runtime:10.0.19041.2788 (WinBuild.160101.0800):Microsoft Corporation
		SHCORE.dll:SHCORE:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		SHELL32.dll:Windows Shell Common Dll:10.0.19041.964 (WinBuild.160101.0800):Microsoft Corporation
		UMPDC.dll
		USER32.dll:Multi-User Windows USER API Client DLL:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		USERENV.dll:Userenv:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		VCRUNTIME140.dll:Microsoftآ® C Runtime Library:14.29.30139.0 built by: vcwrkspc:Microsoft Corporation
		VERSION.dll:Version Checking and File Installation Libraries:10.0.19041.546 (WinBuild.160101.0800):Microsoft Corporation
		WINHTTP.dll:Windows HTTP Services:10.0.19041.2075 (WinBuild.160101.0800):Microsoft Corporation
		WINMM.dll:MCI API DLL:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		WS2_32.dll:Windows Socket 2.0 32-Bit DLL:10.0.19041.1081 (WinBuild.160101.0800):Microsoft Corporation
		WSOCK32.dll:Windows Socket 32-Bit DLL:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		Wldp.dll:Windows Lockdown Policy:10.0.19041.1 (WinBuild.160101.0800):Microsoft Corporation
		amsi.dll:Anti-Malware Scan Interface:10.0.19041.2075 (WinBuild.160101.0800):Microsoft Corporation
		antimalware_provider64.dll:AMSI provider :
		
		
i guess its same error and it got fixed by deleting the config file

**Comment by Dragon-Seeker** [comment] 2023-09-12 04:59
Yes, such is an issue when I fixed the config, the old value broke mod loading until the config is deleted which is due to bad handling on the Config Library chosen.

**Comment by Dragon-Seeker** [comment] 2023-09-14 20:51
An updated version of the mod will be released in the future that will have better error handling for the configs tintColor value

**Comment by Dragon-Seeker** [comment] 2023-09-16 21:22
Such an update has released to hopefully fix this problem from happening

**Closed as completed** 2023-09-17 06:54 UTC
Labels: bug
