### ISSUE TITLE
Crash on exit - v1.16.5

### ISSUE THREAD

**Issue by Sprlptr48** [Minenash/Seamless-Loading-Screen#17] opened 2021-02-04 18:52 UTC
I get an error when leaving a world, happens on both single and multiplayer. The mods i have installed are available in the crash report. 
When i re-enter the game, it works fine, loads the screenshot, but when leaving it crashes. I tried your 1.0 and current github 1.1.1beta.1 and it happens on both of them.

[crash-2021-02-04_21.45.02-client.txt](https://github.com/Minenash/Seamless-Loading-Screen/files/5927825/crash-2021-02-04_21.45.02-client.txt)
I do not know if this file is helpful for you, so you can ask me any question if you need.

**Comment by Minenash** [comment] 2021-02-04 19:23
Duplicate of #15 

I should have a hot-fix ready by tomorrow night

**Closed by Minenash** 2021-02-04 19:23 UTC
